// <auto-generated />
namespace RentingVehicles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DBV15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBV15));
        
        string IMigrationMetadata.Id
        {
            get { return "201807032217163_DBV15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
